apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: tech-challenge-namespace
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: tech-challenge-pos-fiap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
