apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: tech-challenge-namespace
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: tech-challenge-pos-fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/part-of: tech-challenge-pos-fiap
    spec:
      containers:
        - name: mongo
          image: mongo:7.0.21
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: data
              mountPath: /data/db
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-data
